words = {
    'rudimentary':['rudimentary skills'],
    'courtship':['courtship rituals'],
    'ritual':['courtship rituals'],
    'stereoscopic':['stereoscopic vision'],
    'turbid':['turbid water'],
    'repertoire':['musical repertoire'],
    'monotonous':['monotonous job'],
    'speculation':['engage in speculation'],
    'speculate':['speculate about the outcome'],
    'rendition':['artistic rendition'],
    'metaphor':['a vivid metaphor'],
    'metaphorical':['metaphorical language'],
    'perimeter':['calculate the perimeter'],
    'jerk':['jerk off'],
    'visual':['visual arts'],
    'distort':['distort the truth'],
    'expose':['expose the truth'],
    'sponge':['sponge bob'],
    'audition':['audition for a role'],
    'mount':['mount a TV'],
    'announce':['announce the news'],
    'headline':['headline news'],
    'horror':['horror movies'],
    'discriminate':['discriminate against women'],
    'destructive':['The destructive power of the nuclear weapon'],
    'authority':['undermine authority'],
    'authorize':['authorize a payment'],
    'mild':['I really enjoy the mild, breezy weather of spring.'],
    'capacity':['The capacity of the memory card'],
    'latitude':['latitude and longitude'],
    'longitude':['latitude and longitude'],
    'comet':['Halley\'s comet'],
    'grin':['grin emoji'],
    'democratic':['RoC is a democratic country'],
    'faculty':['The faculty of Law'],
    'cucumber':['smacked cucumber'],
    'bizarre':['bizarre behavior'],
    'gravity':['gravity field'],
    'cap':['cap a bottle'],
    'absurd':['an absurd idea'],
    'separate':['separate rooms'],
    'incline':['I incline towards the idea of taking a vacation'],
    'inclination':['I have a natural inclination towards helping others'],
    'pressure':['peer pressure'],
    'convict':['He was convicted of a crime and sentenced to five years in prison'],
    'conviction':['strong conviction'],
    'tranquility':['the tranquility of nature'],
    'facilitate':['facilitate communication'],
    'grand':['a grand celebration'],
    'disapprove':['People today strongly disapprove of gender discrimination.'],
    'responsible':['responsible for promoting gender equality.'],
    'sensitive':['sensitive to criticism'],
    'stressed':['Feeling stressed after an exam.'],
    'stressful':['A stressful situation'],
    'acumen':['I\'ve always respected your business acumen.'],
    'dissertation':['write a dissertation'],
    'heap':['a heap of trouble'],
    'frame':['frame of reference'],
    'installment':['installment plan'],
    'symbolism':['Religious symbolism'],
    'self-esteem':['build your self-esteem'],
    'endanger':['An endangered species'],
    'foster':['foster better relationship'],
    'ancestral':['An ancestral skill'],
    'kindle':['kindle a fire'],
    'rekindle':['rekindle the hope'],
    'revival':['An economic revival'],
    'revive':['revive the economy'],
    'inevitable':['death is inevitable'],
    'disenchantment':['There is growing public disenchantment with the educational system.'],
    'enchant':['enchanted to meet you'],
    'acupuncture':['Chinese acupuncture'],
    'loath':['He was loath to admit his mistake.'],
    'outlook':['Most western countries are liberal in outlook.'],
    'orthodox':['orthodox medicine'],
    'amplify':['amplify a signal'],
    'reliance':['Cut back reliance on fossil fuel.'],
    'rely':['you can only rely on yourself now.'],
    'nightmare':['It\'s a nightmare'],
    'leap':['leap out of the bed'],
    'conscious':['make a conscious decision'],
    'divine':['divine intervention'],
    'decompose':['a decomposed body'],
    'spot on':['His assessment is spot on.'],
    'investigate':['investigate a suspect'],
    'underneath':['We kissed underneath the stars.'],
    'division':['division or labor'],
    'ancient':['ancient history'],
    'strand':['a strand of hair'],
    'specimen':['An animal specimen'],
    'motive':['Money is a good motive.'],
    'furious':['a furious debate'],
    'whaling':['illegal whaling'],
    'exhilarate':['Speed exhilarates me.'],
    'inland':['an inland sea'],
    'migrate':['migrate south for winter'],
    'migrant':['migrant workers'],
    'barrel':['a beer/wine barrel'],
    'claim':['I don\'t claim to be an expert.'],
    'decipher':['decipher a password'],
    'extraordinary':['an extraordinary achievement'],
    'aluminum':['Aluminum foil'],
    'Snap up':['Snap up bargains'],
    'tan':['get a tan'],
    'impair':['noise impair your hearing'],
    'inescapable':['an inescapable fact'],
    'adolescent':['adolescent development'],
    'adolescence':['adolescence development'],
    'associate':['associate professor'],
    'association':['trade association'],
    'pour':['The government has poured money into tackling crime in cities.'],
    'opportunity':['People value every opportunity to escape the city.'],
    'coastline':['coastline erosion'],
    'corn':['corn on the cob'],
    'spear':['spear fishing'],
    'herd':['a herd of cows'],
    'germination':['seed germination'],
    'code':['dress code'],
    'sawdust':['sawdust on the floor'],
    'refrigeration':['refrigeration system'],
    'guinea':['guinea pig'],
    'layer':['Ozone layer'],
    'cable':['cable car'],
    'wedge':['a wedge of cake'],
    'judicious':['a judicious decision'],
    'landfill':['landfill site'],
    'cast':['cast a shadow'],
    'curtain':['draw the curtains'],
    'uniform':['school uniform'],
    'quartz':['a quartz watch'],
    'longitudinal':['a longitudinal study'],
    'disillusion':['he became disillusioned with his job.'],
    'clientele':['an international clientele'],
    'holistic':['a holistic approach'],
    'exodus':['A mass exodus'],
    'concur':['Concurred with you in the idea.'],
    'preventative':['A preventative medicine'],
    'adjunct':['adjunct professor'],
    'simplistic':['A simplistic view'],
    'complementary':['a complementary team'],
    'hiccup':['Have a hiccup'],
    'prowess':['demonstrate prowess'],
    'regress':['Chinese democracy is regressing.'],
    'engross':['An engrossing problem'],
    'tease':['tease sb about sth'],
    'exuberant':['exuberant enthusiasm'],
    'cavort':['SHe cavorted on the beach with her new lover.'],
    'socialize':['You should socialize more.'],
    'sociable':['A sociable person'],
    'molecule':['a water molecule'],
    'regarding':['regarding this matter, we have gathered here'],
    'contact':['make contact with'],
    'creative':['creative thinking'],
    'secondary':['secondary effect'],
    'in favor of':['do you in favor of the union'],
    'dictation':['take dictation'],
    'populate':['populate an area'],
    'merchandising':['branding and merchandising'],
    'dealer':['online dealer'],
    'pore over':['pore over the book'],
    'pore':['open pores'],
    'patriotic':['patriotic song'],
    'compatriot':['fellow compatriots'],
    'envious':['Everyone is so envious of her.'],
    'sibling':['sibling rivalry'],
    'trait':['personality traits'],
    'guardian':['legal guardian'],
    'amusement':['amusement park'],
    'quotation':['quotation marks'],
    'syndrome':['Down\'s syndrome'],
    'chronological':['in chronological order'],
    'squirrel':['Sandy is a squirrel.'],
    'hibernation':['Go into hibernation'],
    'dismissive':['dismissive attitude'],
    'upheaval':['social upheaval'],
    'feasibility':['feasibility study'],
    'mating':['The mating season', 'mate'],
    'parliament':['parliamentary democracy'],
    'incubator':['business incubator'],
    'portfolio':['investment portfolio'],
    'hazel':['hazel nuts'],
    'rack':['bike rack'],
    'vitae':['curriculum vitae'],
    'proficiency':['language proficiency'],
    'scaffold':['scaffolding in education'],
    'peg':['wooden peg'],
    'caravan':['caravan park'],
    'picnic':['picnic basket'],
    'panic':['panic attack'],
    'cartridge':['ink cartridge'],
    'introductory':['introductory price'],
    'rink':['skating rink'],
    'dreadful':['What dreadful weather'],
    'dread':['I dread being sick.'],
    'shuttle':['Shuttle service'],
    'stall':['A market stall'],
    'entail':['The job entails a lot of hard work.'],
    'alchemist':['Albedo is an alchemist'],
    'contrary':['On the contrary'],
    'alert':['It makes them more alert.'],
    'shift':['night shift'],
    'mere':['People turn pale at the mere mention of cancer.'],
    'monitor':['A PC monitor'],
    'derive':['I derived pleasure from learning'],
    'minimal':['A minimal cost'],
    'sketch':['A sketch map'],
    'lag':['Jet lag'],
    'trigger':['Trigger an alarm'],
    'supplement':['Vitamin supplement'],
    'supplementary':['supplementary material'],
    'offend':['It\'s an ugly building that offends the eye.'],
    'offensive':['offensive language'],
    'vivid':['a vivid memory'],
    'as for':['as for me, I\'m leaving this country.'],
    'enclose':['SYSU is enclosed by walls'],
    'dose':['a dose of drug'],
    'supply':['supply power'],
    'compressed':['compressed air'],
    'overcome':['overcome fear'],
    'achievement':['a sense of achievement'],
    'cease':['cease production'],
    'arable':['We turned the desert to arable land.'],
    'congested':['A congested road'],
    'negotiate':['negotiate a deal'],
    'Nordic':['nordic countries'],
    'linger':['her beauty linger in my mind.'],
    'womb':['A mother\'s womb'],
    'advantageous':['In an advantageous position'],
    'manoeuver':['Strategic manoeuver'],
    'converse':['converse with sb'],
    'conversion':['conversion rate'],
    'convert':['convert to energy'],
    'conversely':['conversely, on the other hand'],
    'context':['In the context of globalization'],
    'dearth':['a dearth of information'],
    'adventurous':['adventurous spirit'],
    'exploit':['exploit opportunities'],
    'impoverish':['COVID19 impoverish the poor'],
    'colony':['British colony'],
    'muster':['muster the courage'],
    'vanquish':['vanquish an enemy'],
    'succumb':['succumb to pressure'],
    'elapse':['time has elapsed'],
    'convection':['convection currents'],
    'plateau':['The Qinghai-Tibet plateau'],
    'crust':['Earth\'s crust'],
    'overlie':['overlying rock'],
    'brittle':['brittle nails'],
    'collision':['a head-on collision'],
    'collide':['collide with each other'],
    'extrude':['lava is extruded from the volcano'],
    'pumice':['pumice stone'],
    'predictable':['predictable outcome'],
    'geological':['geological formations'],
    'halve':['a problem shared is a problem halved'],
    'assimilate':['assimilate into society'],
    'assimilation':['cultural assimilation'],
    'harbor':['Pearl harbor'],
    'hybrid':['hybrid vehicle'],
    'inhale':['inhale oxygen'],
    'exhale':['exhale slowly'],
    'decibel':['lower your decibel'],
    'voyage':['maiden voyage'],
    'contingency':['contingency plan'],
    'sake':['for the sake of clarity'],
    'relieve':['relieve stress'],
    'stance':['take a stance'],
    'conduct':['conduct a survey'],
    'conductive':['conductive material'],
    'attack':['under attack'],
    'discredit':['discredit the evidence'],
    'anticipate':['We anticipate your arrival'],
    'operate':['operate a machine'],
    'bypass':['bypass surgery'],
    'undetected':['go undetected'],
    'shaft':['shaft of the axe'],
    'dominate':['dominate the world'],
    'instrumental':['I\'m instrumental in this project.'],
    'determine':['determine the outcome'],
    'load':['load capacity'],
    'sensitive':['sensitive to criticism'],
    'sensible':['a sensible decision'],
    'abolish':['abolish the death penalty'],
    'conception':['from conception to completion'],
    'encounter':['close encounter'],
    'bubble':['bubble sort'],
    'sample':['a sample survey'],
    'qualitative':['qualitative analysis'],
    'accountant':['certified public accountant'],
    'accountancy':['accountancy firm'],
    'plaster':['sticking plaster'],
    'storey':['multi-storey building'],
    'gang':['gang violence'],
    'enterprise':['business enterprise'],
    'verify':['verify your identity'],
    'string':['a string of pearls'],
    'litter':['drop the litter'],
    'manor':['a manor house'],
    'locality':['in the locality of'],
    'breakdown':['breakdown of marriage'],
    'irresistible':['irresistible offer'],
    'fluency':['language fluency'],
    'transcription':['gene transcription'],
    'introspection':['self-introspection'],
    'informant':['confidential informant'],
    'generative':['generative artificial intelligence'],
    'recourse':['legal recourse'],
    'pretzel':['pretzel factory'],
    'provisional':['provisional license'],
    'tent':['pitch a tent'],
    'stunning':['stunning view'],
    'fire drill':['fire drill'],
    'swan':['swan song'],
    'pot':['pot of gold'],
    'express':['express oneself'],
    'fringe':['fringe benefits'],
    'quarantine':['quarantine period'],
    'irrespective':['irrespective of the circumstances'],
    'assortment':['a wide assortment'],
    'promenade':['seafront promenade'],
    'warden':['prison warden'],
    'hedge':['hedge fund'],
    'petition':['sign a petition'],
    'expedition':['scientific expedition'],
    'monogamous':['monogamous relationship'],
    'miniature':['miniature model'],
    'fernery':['indoor fernery'],
    'dustbin':['Consign sth to the dustbin of history'],
    'cranberry':['cranberry sauce'],
    'archaeology':['archaeological dig'],
    'roadworthy':['roadworthy inspection'],
    'hovercraft':['hovercraft ferry service'],
    'rollercoaster':['rollercoaster ride'],
    'vetting':['vetting process'],
    'rendezvous':['secret rendezvous'],
    'paramount':['China\'s paramount leader.'],
    'funnel':['sales funnel'],
    'calligraphy':['calligraphy pen'],
    'flamingo':['flamingo stance'],
    'canoe':['paddle a canoe'],
    'outskirt':['on the outskirts'],
    'venue':['wedding venue'],
    'carton':['a carton of milk'],
    'off-peak':['off-peak hours'],
    'scrupulous':['scrupulous attention to detail'],
    'utter':['utter disbelief'],
    'utterance':['spontaneous utterance'],
    'emeritus':['professor emeritus'],
    'bilingual':['bilingual education'],
    'mundane':['a mundane job'],
    'foreseeable':['foreseeable future'],
    'invoke':['invoke the labor law'],
    'hurl':['hurl a brick'],
    'duplicate':['duplicate key'],
    'mushroom':['mushroom cloud'],
    'elite':['elite athlete'],
    'bury':['bury the hatchet'],
    'bold':['This is a bold move'],
    'bald':['bald eagle'],
    'award':['award ceremony'],
    'hassle':['avoid the hassle'],
    'addict':['a drug addict'],
    'restrain':['restrain oneself'],
    'reproduce':['reproduce the experiment'],
    'signpost':['signpost the way'],
    'artefact':['archaeological artefact'],
    'highland':['highland terrain'],
    'application':['application form'],
    'acquaintance':['casual acquaintance'],
    'challenge':['face a challenge'],
    'guideline':['follow the guidelines'],
    'hemisphere':['northern hemisphere'],
    'civil':['a civil war'],
    'viable':['a viable option'],
    'bicameral':['bicameral system'],
    'gigantic':['gigantic statue'],
    'grieve':['grieve a loss'],
    'studio':['recording studio'],
    'inhabit':['I inhabit the urban area of SZ'],
    'habitat':['a natural habitat'],
    'suicidal':['suicidal thoughts'],
    'bilateral':['bilateral agreement'],
    'clinic':['walk-in clinic'],
    'memorable':['memorable moment'],
    'dazzle':['dazzle the audience'],
    'vast':['a vast expanse of land'],
    'underground':['underground movement'],
    'compete':['compete in a tournament'],
    'prescription':['prescription medication'],
    'prescribe':['prescribe a treatment'],
    'crude':['crude oil'],
    'in vain':['efforts in vain'],
    'alley':['back alley'],
    'dolphin':['dolphin pod'],
    'platform':['online platform'],
    'appoint':['appoint a representative'],
    'characteristic':['defining characteristic'],
    'character':['moral character'],
    'altitude':['high altitude'],
    'contradiction':['logical contradiction'],
    'contradict':['contradict oneself'],
    'painstaking':['painstaking effort'],
    'pursuit':['in pursuit of'],
    'apportion':['apportion blame'],
    'accountable':['be held accountable for'],
    'finitude':['awareness of finitude'],
    'revelation':['sensational revelation'],
    'reveal':['reveal a secret'],
    'attainable':['attainable goals'],
    'dispensable':['I\'m not indispensable.'],
    'cuisine':['local cuisine'],
    'reputable':['reputable source'],
    'reputation':['build a reputation'],
    'overshadow':['overshadow by success'],
    'unparalleled':['unparalleled beauty'],
    'supersede':['supersede existing regulations'],
    'passionate':['a passionate speech'],
    'poisonous':['poisonous snake'],
    'poison':['antidote to poison'],
    'mysterious':['mysterious disappearance'],
    'spite':['Mosquitoes don\'t bite out of spite'],
    'divert':['divert a train'],
    'dissemination':['thermal dissemination'],
    'disseminate':['disseminate information'],
    'perpetual':['perpetual motion machine'],
    'perpetuate':['perpetuate a cycle of'],
    'column':['column in a newspaper'],
    'cater':['cater lunch'],
    'lobby':['a hotel lobby'],
    'flexible':['flexible schedules'],
    'penalty':['the death penalty'],
    'penalize':['penalize for non-compliance'],
    'comply':['comply with the law'],
    'racket':['a tennis racket'],
    'socket':['Plug the charger into the wall socket'],
    'capsule':['take a capsule'],
    'canteen':['a school canteen'],
    'aeronautics':['a professor of aeronautics.'],
    'adopt':['adopt pets'],
    'lease':['You claim to be a tenant, yet you have no lease.'],
    'conceal':['conceal identity'],
    'haphazard':['The books were stacked in a haphazard manner.'],
    'essential':['essential ingredient'],
    'urge':['She urged him to stay.'],
    'feasible':['a feasible plan'],
    'cereal':['Calbee cereal'],
    'slurry':['slurry pump'],
    'admission':['admission to the college'],
    'jaw':['jaw-dropping'],
    'subtract':['6 subtracted from 9 is 3.'],
    'linguistic':['linguistic diversity'],
    'aptitude':['aptitude test'],
    'lava':['lava flow'],
    'premier':['Premier League'],
    'enquiry':['make an enquiry'],
    'lawsuit':['file a lawsuit'],
    'pack':['a pack of dogs'],
    'animate':['animate objects'],
    'animation':['computer animation'],
    'availability':['check your availability'],
    'payable':['a 10% deposit is payable in advance'],
    'solicitor':['I need my solicitor.'],
    'departure':['departure lounge'],
    'depart':['depart from 3 for America'],
    'audit':['an annual audit'],
    'scamper':['scamper away'],
    'spiral':['spiral abyss'],
    'encode':['encode a message'],
    'scout':['scout for talents'],
    'regurgitate':['regurgitate food'],
    'propellant':['Rocket propellant'],
    'ejection':['ejection seat'],
    'eject':['eject from a vehicle'],
    'barrage':['a barrage of questions'],
    'intrigue':['This Mr. Sherlock Holmes intrigues me.'],
    'transition':['transition period'],
    'realm':['in the realm of literature'],
    'banner':['banner year'],
    'ounce':['an ounce of prevention is worth a pound of cure.'],
    'technique':['a traditional technique'],
    'stock':['stock market'],
    'stack':['stack up against'],
    'petrol':['We ran out of petrol'],
    'sorrow':['drown one\'s sorrows'],
    'arboreal':['arboreal animal'],
    'facade':['the facade of a church'],
    'post-mortem':['conduct a post-mortem'],
    'blunt':['a blunt refusal'],
    'pile':['a pile of work'],
    'post':['police post'],
    'stockpile':['the stockpile of nuclear weapon'],
    'indicate':['indicate interest'],
    'indication':['give no indication'],
    'hypothesis':['test a hypothesis'],
    'hypothetical':['a hypothetical question'],
    'mountainous':['a mountainous region'],
    'trim':['trim the fat'],
    'steady':['a steady barrage'],
    'dramatic':['a dramatic effect'],
    'amorphous':['amorphous material'],
    'blade':['a sharp blade'],
    'glimpse':['he caught a glimpse of her in the crowd'],
    'bulletin':['news bulletin'],
    'chapel':['a wedding chapel'],
    'subscribe':['subscribe apple music'],
    'foil':['aluminum foil'],
    'invoice':['this is your invoice'],
    'transmute':['lead can\'t be transmute into gold'],
    'acoustic':['acoustic guitar'],
    'breakthrough':['a scientific breakthrough'],
    'spiritual':['spiritual journey'],
    'concrete':['concrete evidence'],
    'generalize':['Don\'t over-generalize'],
    'clot':['a blood clot'],
    'prior':['a prior criminal record'],
    'exemplify':['exemplify the best'],
    'herdsman':['a herdsman and his flock'],
    'exploratory':['exploratory research'],
    'pasture':['The cattle were put out to pasture.'],
    'nutrient':['a lack of essential nutrient'],
    'nutritional':['nutritional value'],
    'nutritious':['nutritious fruit'],
    'plough':['plough a field'],
    'scrub':['scrub the floor'],
    'formality':['a mere formality'],
    'perk':['job perk'],
    'heighten':['heighten awareness'],
    'necessity':['Water is necessity in every procedure of making tofu.'],
    'disposable':['a disposable diaper'],
    'ingenuity':['a testament to human ingenuity'],
    'simplicity':['the beauty of simplicity'],
    'luxuriant':['I want luxuriant hair'],
    'consequential':['consequential decision'],
    'consequent':['consequent effects'],
    'consequence':['face the consequences'],
    'scour':['scour the area'],
    'murky':['murky waters'],
    'melatonin':['melatonin supplement'],
    'cue':['cue me'],
    'thermal':['hydrothermal vent'],
    'revolution':['The French revolution'],
    'romance':['an office romance'],
    'recurrent':['a recurrent theme'],
    'persist':['persist in efforts to do my best'],
    'stash':['stash money'],
    'species':['an extinguished species'],
    'competent':['competent authority'],
    'loose':['tie up loose ends'],
    'lose':['I lost my key'],
    'lost':['get lost in thought'],
    'loosen':['loosen up'],
    'carpentry':['carpentry skills'],
    'spreadsheet':['spreadsheet software'],
    'clerical':['clerical work'],
    'Sweden':['Sweden'],
    'myth':['bust a myth'],
    'buffet':['a buffet lunch'],
    'sauna':['take a sauna'],
    'settlement':['reach a settlement'],
    'otter':['playful otters'],
    'robber':['a bank robber'],
    'midday':['midday sun'],
    'massage':['massage oil'],
    'hoover':['to hoover up all the dust'],
    'hippo':['hungry hippo'],
    'cram':['cram for a test'],
    'cannibal':['cannibal tribes'],
    'annex':['annex a territory'],
    'wretch':['a poor wretch'],
    'wholesale':['wholesale prices'],
    'timetable':['train timetable'],
    'tertiary':['tertiary education'],
    'suntan':['suntan block'],
    'suite':['standard suite'],
    'spinose':['spinose plants'],
    'shear':['shear the sheep'],
    'urchin':['sea urchin'],
    'rubber':['rubber band'],
    'slice':['a slice of pizza'],
    'waterfront':['waterfront property'],
    'cricket':['cricket match'],
    'swell':['My toe swelled up like a balloon.'],
    'swelling':['reduce swelling'],
    'synthesis':['protein synthesis'],
    'synthetic':['synthetic fiber'],
    'excreta':['human excreta'],
    'decapitate':['a decapitate body'],
    'pepper':['black pepper'],
    'groan':['let out a groan'],
    'upset':['a stomach upset'],
    'appeal':['make an appeal'],
    'consumption':['fuel consumption'],
    'caution':['proceed with caution'],
    'burst':['burst into tears'],
    'ecology':['ecosystem ecology'],
    'ecological':['ecological balance'],
    'highway':['highway patrol'],
    'launch':['product launch'],
    'medieval':['medieval times'],
    'concede':['concede defeat'],
    'chef':['a head chef'],
    'fade':['I saw the light fade from the sky.'],
    'behave':['behave yourself'],
    'dredge':['dredge a river'],
    'irritable':['an irritable gesture'],
    'legislation':['pass legislation'],
    'legislative':['legislative process'],
    'bouncing':['a bouncing girl'],
    'sizeable':['a sizeable amount of money'],
    'innovative':['innovative solutions'],
    'innovation':['technological innovation'],
    'particulate':['particulate matter'],
    'pollutant':['air pollutant'],
    'megacity':['megacity population'],
    'allergic':['Wendy is allergic to cats.'],
    'populace':['the general populace'],
    'proclaim':['proclaim independence'],
    'comparable':['comparable to'],
    'habitual':['habitual behavior'],
    'rehabilitate':['rehabilitate an injury'],
    'picturesque':['a picturesque village'],
    'afield':['Your remarks are far afield'],
    'spill':['spill the beans'],
    'tedious':['a tedious task'],
    'mediocre':['mediocre performance'],
    'productive':['productive day'],
    'productivity':['increase productivity'],
    'respond':['respond to an email'],
    'responsible':['be responsible for yourself'],
    'approval':['seek approval'],
    'flaw':['a fatal flaw'],
    'multiple':['multiple choices'],
    'multiply':['2 multiplied by 4 is 8'],
    'adventure':['seek adventure'],
    'diagram':['flow chart diagram'],
    'slouch':['don\'t slouch'],
    'bloom':['in full bloom'],
    'trick':['play a trick on sb.'],
    'centigrade':['30 degrees centigrade'],
    'Celsius':['30 degrees Celsius'],
    'Fahrenheit':['60 degrees Fahrenheit'],
    'courageous':['a courageous decision'],
    'quarry':['stone quarry'],
    'precious':['precious stone'],
    'precaution':['take precautions'],
    'pal':['the best pal'],
    'hitchhike':['hitchhike across the country'],
    'projector':['movie projector'],
    'overdue':['overdue and pay a fine'],
    'out on loan':['the book you wanted is out on loan'],
    'oriental':['oriental rug'],
    'obligatory':['obligatory courses'],
    'nursery':['nursery'],
    'martial':['martial arts'],
    'instant':['instant coffee'],
    'haunt':['haunted house'],
    'honeymoon':['honeymoon phase'],
    'preferable':['Working from home is preferable to commuting during rush hour.'],
    'biometric':['biometric data'],
    'reunite':['reunite with family'],
    'minority':['ethnic minority'],
    'clench':['He clenched his fists in anger.'],
    'corpus':['corpus linguistics'],
    'beam':['a beam ofl light'],
    'conjunction':['in conjunction with'],
    'nasty':['nasty surprise'],
    'adequate':['adequate resources'],
    'incentive':['financial incentive'],
    'inventive':['an inventive solution'],
    'chorus':['join the chorus'],
    'scent':['scent of garlic'],
    'hitherto':['a hitherto unknown species'],
    'bullet':['take a bullet'],
    'enclosure':['a wildlife enclosure'],
    'revegetate':['revegetate to backyard'],
    'sustain':['sustain growth'],
    'sustainable':['sustainable development'],
    'dispersal':['seed dispersal'],
    'fabulous':['look fabulous'],
    'rental':['a rental car'],
    'rent':['rent a house'],
    'obsession':['His obsession with perfection often gets in the way of completing project on time.'],
    'fraught':['It\'s a time fraught with difficulties.'],
    'ethereal':['ethereal beauty'],
    'obtrusive':['obtrusive advertising'],
    'underpin':['Use extensive data to underpin the report'],
    'velocity':['the velocity of light'],
    'unveil':['unveil a new product'],
    'swivel':['a swivel chair'],
    'replicate':['replicate the result'],
    'capsize':['capsize a boat'],
    'drum':['play the drum'],
    'thorny':['thorny problem'],
    'eligible':['Employees are eligible for the company\'s stock option plan]'],
    'enrolment':['enrolment fee'],
    'enroll':['enroll in a course'],
    'emerge':['emerge victorious'],
    'submerge':['submerge underwater'],
    'granite':['granite countertop'],
    'approximate':['an approximate value'],
    'gallery':['an art gallery'],
    'swing':['swing into action'],
    'spectrum':['broad spectrum'],
    'vested':['vested interest'],
    'symphony':['symphony orchestra'],
    'alter':['alter the course'],
    'disqualify':['disqualify from competition'],
    'administer':['administer a test'],
    'administrator':['system administrator'],
    'inventory':['inventory management'],
    'aeration':['soil aeration'],
    'profitable':['profitable business'],
    'virus':['computer virus'],
    'faith':['leap of faith'],
    'cafeteria':['cafeteria'],
    'dairy':['dairy cow'],
    'confirm':['confirm a rumor'],
    'hinge':['hinge on'],
    'subsidy':['government subsidies'],
    'stain':['remove a stain'],
    'unload':['unload goods'],
    'irrelevant':['irrelevant information'],
    'relevant':['relevant information'],
    'thrill':['seek a thrill'],
    'extol':['extol the virtues'],
    'albeit':['She achieve her goal, albeit difficult, by sheer determination and hard work.'],
    'obstacle':['overcome an obstacle'],
    'meagre':['meagre resources'],
    'precipitation':['annual precipitation'],
    'precarious':['in a precarious situation'],
    'autonomy':['personal autonomy'],
    'onslaught':['onslaught of criticism'],
    'curtail':['curtail spending'],
    'correlation':['correlation does not imply causation'],
    'afflict':['afflict the population'],
    'afflicting':['knowing the truth is afflicting'],
    'incongruous':['looks incongruous with'],
    'incongruity':['sense of incongruity'],
    'hoof':['We hoofed it all the way to 42nd Street.'],
    'timber':['timber industry'],
    'medal':['win a gold medal'],
    'executive':['executive decision'],
    'falcon':['falcons is birds of prey.'],
    'engrave':['engrave a message'],
    'circus':['circus performance'],
    'charitable':['charitable organization'],
    'call slip':['call slip'],
    'circulation desk':['circulation desk'],
    'prone':['He\'s always been prone to accidents.'],
    'antibiotics':['antibiotics resistance'],
    'agrarian':['agrarian reform'],
    'scare':['You scare me.'],
    'scarce':['scarce resources'],
    'troublesome':['troublesome issue'],
    'spacious':['a spacious room'],
    'slim':['a slim chance of success'],
    'sack':['He was sacked from the job.'],
    'Olympic':['Olympic athlete'],
    'noble':['a noble cause'],
    'foreign':['foreign countries'],
    'fame':['to rise to fame overnight'],
    'coastal':['coastal area'],
    'advisable':['It is advisable to'],
    'vinegar':['apple cider vinegar'],
    'jargon':['computer jargon'],
    'syrup':['corn syrup'],
    'sandal':['summer sandals'],
    'refuge':['seek refuge'],
    'oculist':['see an oculist'],
    'nap':['take a nap'],
    'morality':['private morality'],
    'mill':['grain mill'],
    'mane':['lion\'s mane'],
    'encyclopedia':['encyclopedia'],
    'cabinet':['a cabinet meeting'],
    'remuneration':['remuneration package'],
    'intermix':['intermix colors'],
    'hypnotic':['a hypnotic room'],
    'mainstream':['mainstream media'],
    'stir':['stir up trouble'],
    'inject':['inject funds'],
    'wagon':['jump on the bandwagon'],
    'tag':['price tag'],
    'excursion':['go on an excursion'],
    'dizzy':['a dizzy spell'],
    'immune':['the immune system'],
    'carve':['carve out a niche'],
    'droplet':['a droplet of sweat'],
    'cholesterol':['Yolk is full of cholesterol'],
    'calcium':['calcium deficiency'],
    'interval':['time interval'],
    'advent':['with the advent of technology'],
    'category':['category of products'],
    'wrinkle':['iron out the wrinkles on the dress'],
    'huddle':['team huddle'],
    'marble':['a marble status'],
    'booth':['voting booth'],
    'cohesion':['social cohesion'],
    'astound':['astound me a lot'],
    'absorb':['absorb information'],
    'livestock':['livestock farming'],
    'weigh':['weigh the options'],
    'ceramic':['ceramic tile'],
    'acquisition':['corporate acquisition'],
    'entice':['entice customer'],
    'retrenchment':['corporate retrenchment'],
    'infirmity':['old age infirmity'],
    'extravagance':['luxurious extravagance'],
    'extravagant':['extravagant lifestyle'],
    'victimize':['victimize innocent people'],
    'victim':['victim of crime'],
    'maternal':['maternal instinct'],
    'crusade':['to lead a crusade against crime'],
    'recalcitrant':['recalcitrant behavior'],
    'mortality':['mortality rate'],
    'mortal':['a mortal wound'],
    'taunt':['taunt someone.'],
    'sanction':['economic sanctions'],
    'invert':['invert the bottle upside down'],
    'recipe':['recipe for success'],
    'receipt':['make out a receipt'],
    'condense':['condense information'],
    'condensation':['water condensation'],
    'cantonese':['speak cantonese'],
    'advertise':['advertise a product'],
    'irrevocable':['irrevocable decision'],
    'shelter':['seek shelter'],
    'devise':['devise a plan'],
    'device':['electronic device'],
    'hollow':['hollow sound'],
    'bark':['bark of a tree'],
    'burrow':['animal burrow'],
    'equivalent':['is equivalent to'],
    'fatigue':['combat fatigue'],
    'bibliography':['annotated bibliography'],
    'probable':['the probable cause of his death'],
    'probability':['probability theory'],
    'fortnight':['fortnightly payment'],
    'treadmill':['treadmill workout'],
    'asymmetry':['facial asymmetry'],
    'lethal':['a lethal dose of poison'],
    'stare':['Why are you all staring at me.'],
    'bungalow':['single-story bungalow'],
    'stab':['stab wound'],
    'flint':['flint and steel'],
    'commodity':['commodity market'],
    'lane':['traffic lane'],
    'punctual':['a punctual arrival'],
    'intake':['daily intake of salt'],
    'penetration':['The floor is sealed to prevent water penetration'],
    'municipal':['municipal district'],
    'deficit':['a budget deficit'],
    'triumphant':['triumphant return'],
    'triumph':['triumph over adversity'],
    'circumscribe':['circumscribe the power'],
    'patronage':['political patronage'],
    'analogy':['draw an analogy'],
    'analogous':['analogous situation'],
    'precedent':['legal precedent'],
    'precede':['the preceding night'],
    'obscurity':['rise from obscurity'],
    'ascertain':['ascertain the truth'],
    'legitimacy':['political legitimacy'],
    'legitimate':['legitimate concern'],
    'legitimize':['legitimize authority'],
    'discrepancy':['resolve the discrepancy'],
    'benevolent':['benevolent act'],
    'downsize':['downsize the workforce'],
    'glitter':['all that glitters is not gold'],
    'subsequent':['subsequent events'],
    'council':['city council'],
    'venomous':['venomous snake'],
    'venom':['snake venom'],
    'intellectual':['intellectual property'],
    'intelligible':['make it intelligible'],
    'intelligence':['artificial intelligence'],
    'leukemia':['treatment for leukemia'],
    'centennial':['a centennial celebration'],
    'mediterranean':['mediterranean country'],
    'outdo':['outdo oneself'],
    'discipline':['self-discipline'],
    'fulfill':['fulfill a promise'],
    'fulfillment':['personal fulfillment'],
    'segment':['market segment'],
    'delegate':['delegate responsibility'],
    'radiate':['radiate confidence'],
    'radiation':['radiation therapy'],
    'situated':['situated in a remote valley'],
    'kit':['emergency kit'],
    'stove':['gas stove'],
    'bucket':['bucket list'],
    'owl':['nocturnal owl'],
    'absenteeism':['reduce absenteeism'],
    'minister':['The prime minister'],
    'apparent':['apparent reason'],
    'combustion':['combustion engine'],
    'plausible':['plausible explanation'],
    'transient':['transient population'],
    'altruistic':['altruistic behavior'],
    'pragmatic':['pragmatic approach'],
    'dwindle':['dwindling audiences'],
    'disdain':['look of disdain'],
    'constituent':['constituent part'],
    'impetus':['His articles provided the main impetus for change.'],
    'malleable':['malleable alloy'],
    'renaissance':['renaissance art'],
    'instinct':['primitive instinct'],
    'pedigree':['a noble pedigree'],
    'scuffle':['break up a scuffle'],
    'treatise':['scholarly treatise'],
    'smother':['smother the flames'],
    'excess':['excess baggage'],
    'excessive':['excessive consumption'],
    'spine':['spinal cord'],
    'smooth':['smooth transition'],
    'incur':['incur costs'],
    'confine':['confine to a space'],
    'curb':['curb your appetite'],
    'sip':['sip your wine'],
    'pathology':['clinical pathology'],
    'mood':['set the mood'],
    'aridity':['aridity index'],
    'vision':['have a poor vision'],
    'sausage':['pork sausage'],
}

import random

words = {
    'rudimentary': ['rudimentary skills'],
    'courtship': ['courtship rituals'],
    'ritual': ['courtship rituals'],
    'stereoscopic': ['stereoscopic vision'],
}

def review_words(words):
    total_words = len(words)
    print(f"Review Overview: You have {total_words} words to review.\n")

    keys = list(words.keys())
    random.shuffle(keys)  # 打乱顺序以随机选择单词

    incorrect_words = {}  # 存储未正确回答的单词
    correct_count = 0  # 正确回答的数量

    for key in keys:
        first_phrase = words[key][0]
        word_count = len(first_phrase.split())
        print(f"Word to review:\n{key}. (First phrase word count: {word_count})")
        user_input = input("Type a phrase or sentence using the word (or press Enter to skip): ").lower()

        # 检查输入是否与任何value的元素匹配
        if any(user_input == phrase.lower() for phrase in words[key]):
            correct_count += 1
            print(f"Correct! The correct answer was:\n{first_phrase}\n")
        else:
            incorrect_words[key] = words[key]
            print(f"Incorrect. The correct answers were:\n{', '.join(words[key])}\n")

    # 所有单词复习完成后的统计和输出
    print(f"Review session complete. Correct: {correct_count}/{total_words} ({(correct_count/total_words)*100:.2f}%).")

    if incorrect_words:
        print("\nWords to review again:")
        for key, value in incorrect_words.items():
            print(f"{key}: {value}")

    return incorrect_words

incorrect_words = review_words(words)

# 如果需要，你可以再次调用 review_words 函数来复习不正确的单词
# incorrect_words = review_words(incorrect_words)