words = {
    # word:['phrase of word','relative word'],
    'rudimentary':['rudimentary skills'],
    'courtship':['courtship rituals'],
    'ritual':['courtship rituals'],
    'stereoscopic':['stereoscopic vision'],
    'turbid':['turbid water'],
    'repertoire':['musical repertoire'],
    'monotonous':['monotonous job'],
    'speculation':['engage in speculation'],
    'speculate':['speculate about the outcome'],
    'rendition':['artistic rendition'],
    'metaphor':['a vivid metaphor'],
    'metaphorical':['metaphorical language'],
    'perimeter':['calculate the perimeter'],
    'jerk':['jerk off'],
    'visual':['visual arts'],
    'distort':['distort the truth'],
    'expose':['expose the truth'],
    'sponge':['sponge bob'],
    'audition':['audition for a role'],
    'mount':['mount a TV'],
    'announce':['announce the news'],
    'headline':['headline news'],
    'horror':['horror movies'],
    'discriminate':['discriminate against women'],
    'destructive':['The destructive power of the nuclear weapon'],
    'authority':['undermine authority'],
    'authorize':['authorize a payment'],
    'mild':['I really enjoy the mild, breezy weather of spring.'],
    'capacity':['The capacity of the memory card'],
    'latitude':['latitude and longitude'],
    'longitude':['latitude and longitude'],
    'comet':['Halley\'s comet'],
    'grin':['grin emoji'],
    'democratic':['RoC is a democratic country'],
    'faculty':['The faculty of Law'],
    'cucumber':['smacked cucumber'],
    'bizarre':['bizarre behavior'],
    'gravity':['gravity field'],
    'cap':['cap a bottle'],
    'absurd':['an absurd idea'],
    'separate':['separate rooms'],
    'incline':['I incline towards the idea of taking a vacation'],
    'inclination':['I have a natural inclination towards helping others'],
    'pressure':['peer pressure'],
    'convict':['He was convicted of a crime and sentenced to five years in prison'],
    'conviction':['strong conviction'],
    'tranquility':['the tranquility of nature'],
    'facilitate':['facilitate communication'],
    'grand':['a grand celebration'],
    'disapprove':['People today strongly disapprove of gender discrimination.'],
    'responsible':['responsible for promoting gender equality.'],
    'sensitive':['sensitive to criticism'],
    'stressed':['Feeling stressed after an exam.'],
    'stressful':['A stressful situation'],
    'acumen':['I\'ve always respected your business acumen.'],
    'dissertation':['write a dissertation'],
    'heap':['a heap of trouble'],
    'frame':['frame of reference'],
    'installment':['installment plan'],
    'symbolism':['Religious symbolism'],
    'self-esteem':['build your self-esteem'],
    'endanger':['An endangered species'],
    'foster':['foster better relationship'],
    'ancestral':['An ancestral skill'],
    'kindle':['kindle a fire'],
    'rekindle':['rekindle the hope'],
    'revival':['An economic revival'],
    'revive':['revive the economy'],
    'inevitable':['death is inevitable'],
    'disenchantment':['There is growing public disenchantment with the educational system.'],
    'enchant':['enchanted to meet you'],
    'acupuncture':['Chinese acupuncture'],
    'loath':['He was loath to admit his mistake.'],
    'outlook':['Most western countries are liberal in outlook.'],
    'orthodox':['orthodox medicine'],
    'amplify':['amplify a signal'],
    'reliance':['Cut back reliance on fossil fuel.'],
    'rely':['you can only rely on yourself now.'],
    'nightmare':['It\'s a nightmare'],
    'leap':['leap out of the bed'],
    'conscious':['make a conscious decision'],
    'divine':['divine intervention'],
    'decompose':['a decomposed body'],
    'spot on':['His assessment is spot on.'],
    'investigate':['investigate a suspect'],
    'underneath':['We kissed underneath the stars.'],
    'division':['division or labor'],
    'ancient':['ancient history'],
    'strand':['a strand of hair'],
    'specimen':['An animal specimen'],
    'motive':['Money is a good motive.'],
    'furious':['a furious debate'],
    'whaling':['illegal whaling'],
    'exhilarate':['Speed exhilarates me.'],
    'inland':['an inland sea'],
    'migrate':['migrate south for winter'],
    'migrant':['migrant workers'],
    'barrel':['a beer/wine barrel'],
    'claim':['I don\'t claim to be an expert.'],
    'decipher':['decipher a password'],
    'extraordinary':['an extraordinary achievement'],
    'aluminum':['Aluminum foil'],
    'Snap up':['Snap up bargains'],
    'tan':['get a tan'],
    'impair':['noise impair your hearing'],
    'inescapable':['an inescapable fact'],
    'adolescent':['adolescent development'],
    'adolescence':['adolescence development'],
    'associate':['associate professor'],
    'association':['trade association'],
    'pour':['The government has poured money into tackling crime in cities.'],
    'opportunity':['People value every opportunity to escape the city.'],
    'coastline':['coastline erosion'],
    'corn':['corn on the cob'],
    'spear':['spear fishing'],
    'herd':['a herd of cows'],
    'germination':['seed germination'],
    'code':['dress code'],
    'sawdust':['sawdust on the floor'],
    'refrigeration':['refrigeration system'],
    'guinea':['guinea pig'],
    'layer':['Ozone layer'],
    'cable':['cable car'],
    'wedge':['a wedge of cake'],
    'judicious':['a judicious decision'],
    'landfill':['landfill site'],
    'cast':['cast a shadow'],
    'curtain':['draw the curtains'],
    'uniform':['school uniform'],
    'quartz':['a quartz watch'],
    'longitudinal':['a longitudinal study'],
    'disillusion':['he became disillusioned with his job.'],
    'clientele':['an international clientele'],
    'holistic':['a holistic approach'],
    'exodus':['A mass exodus'],
    'concur':['Concurred with you in the idea.'],
    'preventative':['A preventative medicine'],
    'adjunct':['adjunct professor'],
    'simplistic':['A simplistic view'],
    'complementary':['a complementary team'],
    'hiccup':['Have a hiccup'],
    'prowess':['demonstrate prowess'],
    'regress':['Chinese democracy is regressing.'],
    'engross':['An engrossing problem'],
    'tease':['tease sb about sth'],
    'exuberant':['exuberant enthusiasm'],
    'cavort':['SHe cavorted on the beach with her new lover.'],
    'socialize':['You should socialize more.'],
    'sociable':['A sociable person'],
    'molecule':['a water molecule'],
    'regarding':['regarding this matter, we have gathered here'],
    'contact':['make contact with'],
    'creative':['creative thinking'],
    'secondary':['secondary effect'],
    'in favor of':['do you in favor of the union'],
    'dictation':['take dictation'],
    'populate':['populate an area'],
    'merchandising':['branding and merchandising'],
    'dealer':['online dealer'],
    'pore over':['pore over the book'],
    'pore':['open pores'],
    'patriotic':['patriotic song','patriot'],
    'compatriot':['fellow compatriots'],
    'envious':['Everyone is so envious of her.'],
    'sibling':['sibling rivalry'],
    'trait':['personality traits'],
    'guardian':['legal guardian'],
    'amusement':['amusement park'],
    'quotation':['quotation marks'],
    'syndrome':['Down\'s syndrome'],
    'chronological':['in chronological order'],
    'squirrel':['Sandy is a squirrel.'],
    'hibernation':['Go into hibernation'],
    'dismissive':['dismissive attitude'],
    'upheaval':['social upheaval'],
    'feasibility':['feasibility study'],
    'mating':['The mating season', 'mate'],
    'parliament':['parliamentary democracy'],
    'incubator':['business incubator'],
    'portfolio':['investment portfolio'],
    'hazel':['hazel nuts'],
    'rack':['bike rack'],
    'vitae':['curriculum vitae'],
    'proficiency':['language proficiency'],
    'scaffold':['scaffolding in education'],
    'peg':['wooden peg'],
    'caravan':['caravan park'],
    'picnic':['picnic basket'],
    'panic':['panic attack'],
    'cartridge':['ink cartridge'],
    'introductory':['introductory price'],
    'rink':['skating rink'],
    'dreadful':['What dreadful weather'],
    'dread':['I dread being sick.'],
    'shuttle':['Shuttle service'],
    'stall':['A market stall'],
    'entail':['The job entails a lot of hard work.'],
    'alchemist':['Albedo is an alchemist','alchemy'],
    'contrary':['On the contrary'],
    'alert':['It makes them more alert.'],
    'shift':['night shift'],
    'mere':['People turn pale at the mere mention of cancer.'],
    'monitor':['A PC monitor'],
    'derive':['I derived pleasure from learning'],
    'minimal':['A minimal cost'],
    'sketch':['A sketch map'],
    'lag':['Jet lag'],
    'trigger':['Trigger an alarm'],
    'supplement':['Vitamin supplement','supplementary'],
    'offend':['It\'s an ugly building that offends the eye.','offensive'],
    'vivid':['a vivid memory'],
    'as for':['as for me, I\'m leaving this country.'],
    'enclose':['SYSU is enclosed by walls'],
    'dose':['a dose of drug'],
    'supply':['supply power'],
    'compressed':['compressed air'],
    'overcome':['overcome fear'],
    'achievement':['a sense of achievement'],
    'cease':['cease production'],
    'arable':['We turned the desert to arable land.'],
    'congested':['A congested road','congestion'],
    'negotiate':['negotiate a deal'],
    'Nordic':['nordic countries'],
    'linger':['her beauty linger in my mind.'],
    'womb':['A mother\'s womb'],
    'advantageous':['In an advantageous position'],
    'manoeuver':['Strategic manoeuver'],
    'converse':['converse with sb'],
    'conversion':['conversion rate','convert'],
    'conversely':['conversely, on the other hand'],
    'context':['In the context of globalization'],
    'dearth':['a dearth of information'],
    'adventurous':['adventurous spirit'],
    'exploit':['exploit opportunities','exploitative, exploitation'],
    'impoverish':['COVID19 impoverish the poor','impoverished'],
    'colony':['British colony'],
    'muster':['muster the courage'],
    'vanquish':['vanquish an enemy'],
    'succumb':['succumb to pressure'],
    'elapse':['time has elapsed'],
    'convection':['convection currents'],
    'plateau':['The Qinghai-Tibet plateau'],
    'crust':['Earth\'s crust'],
    'overlie':['overlying rock'],
    'brittle':['brittle nails'],
    'collision':['a head-on collision','collide'],
    'extrude':['lava is extruded from the volcano'],
    'pumice':['pumice stone'],
    'predictable':['predictable outcome'],
    'geological':['geological formations','geologist geology'],
    'halve':['a problem shared is a problem halved'],
    'assimilate':['assimilate into society','assimilation'],
    'harbor':['Pearl harbor'],
    'hybrid':['hybrid vehicle'],
    'inhale':['inhale oxygen'],
    'exhale':['exhale slowly'],
    'decibel':['lower your decibel'],
    'voyage':['maiden voyage'],
    'contingency':['contingency plan'],
    'sake':['for the sake of clarity'],
    'relieve':['relieve stress'],
    'stance':['take a stance'],
    'conduct':['conduct a survey'],
    'conductive':['conductive material'],
    'attack':['under attack'],
    'discredit':['discredit the evidence'],
    'anticipate':['We anticipate your arrival','n. anticipation'],
    'operate':['operate a machine'],
    'bypass':['bypass surgery'],
    'undetected':['go undetected'],
    'shaft':['shaft of the axe'],
    'dominate':['dominate the world','n domination'],
    'instrumental':['I\'m instrumental in this project.'],
    'determine':['determine the outcome'],
    'load':['load capacity'],
    'sensitive':['sensitive to criticism','n sensitivity'],
    'sensible':['a sensible decision'],
    'abolish':['abolish the death penalty'],
    'conception':['from conception to completion'],
    'encounter':['close encounter'],
    'bubble':['bubble sort'],
    'sample':['a sample survey'],
    'qualitative':['qualitative analysis'],
    'accountant':['certified public accountant','accountancy'],
    'plaster':['sticking plaster'],
    'storey':['multi-storey building'],
    'gang':['gang violence'],
    'enterprise':['business enterprise'],
    'verify':['verify your identity','n identification'],
    'string':['a string of pearls'],
    'litter':['drop the litter'],
    'manor':['a manor house'],
    'locality':['in the locality of','v','locate','n','location'],
    'breakdown':['breakdown of marriage'],
    'irresistible':['irresistible offer'],
    'fluency':['language fluency'],
    'transcription':['gene transcription'],
    'introspection':['self-introspection'],
    'informant':['confidential informant'],
    'generative':['generative artificial intelligence','v','generate'],
    'recourse':['legal recourse'],
    'pretzel':['pretzel factory'],
    'provisional':['provisional license'],
    'tent':['pitch a tent'],
    'stunning':['stunning view'],
    'fire drill':['fire drill'],
    'swan':['swan song'],
    'pot':['pot of gold'],
    'express':['express oneself'],
    'fringe':['fringe benefits'],
    'quarantine':['quarantine period'],
    'irrespective':['irrespective of the circumstances'],
    'assortment':['a wide assortment'],
    'promenade':['seafront promenade'],
    'warden':['prison warden'],
    'hedge':['hedge fund'],
    'petition':['sign a petition'],
    'expedition':['scientific expedition'],
    'monogamous':['monogamous relationship'],
    'miniature':['miniature model'],
    'fernery':['indoor fernery'],
    'dustbin':['Consign sth to the dustbin of history'],
    'cranberry':['cranberry sauce'],
    'archaeology':['archaeological dig'],
    'roadworthy':['roadworthy inspection'],
    'hovercraft':['hovercraft ferry service'],
    'rollercoaster':['rollercoaster ride'],
    'vetting':['vetting process'],
    'rendezvous':['secret rendezvous'],
    'paramount':['China\'s paramount leader.'],
    'funnel':['sales funnel'],
    'calligraphy':['calligraphy pen'],
    'flamingo':['flamingo stance'],
    'canoe':['canoeing adventure'],
    'outskirt':['on the outskirts'],
    'venue':['wedding venue'],
    'carton':['a carton of milk'],
    'off-peak':['off-peak hours'],
    'scrupulous':['scrupulous attention to detail'],
    'utter':['utter disbelief','n','utterance'],
    'emeritus':['professor emeritus'],
    'bilingual':['bilingual education'],
    'mundane':['a mundane job'],
    'foreseeable':['foreseeable future'],
    'invoke':['invoke the labor law'],
    'hurl':['hurl a brick'],
    'duplicate':['duplicate key'],
    'mushroom':['mushroom cloud'],
    'elite':['elite athlete'],
    'bury':['bury the hatchet'],
    'bold':['This is a bold move'],
    'bald':['bald eagle'],
    'award':['award ceremony'],
    'hassle':['avoid the hassle'],
    'addict':['a drug addict','n','addiction'],
    'restrain':['restrain oneself'],
    'reproduce':['reproduce the experiment'],
    'signpost':['signpost the way'],
    'artefact':['archaeological artefact'],
    'highland':['highland terrain'],
    'application':['application form','v','apply','n','applicant'],
    'acquaintance':['casual acquaintance','v','acquaint'],
    'challenge':['face a challenge'],
    'guideline':['follow the guidelines'],
    'hemisphere':['northern hemisphere'],
    'civil':['a civil war'],
    'viable':['a viable option','n','viability'],
    'bicameral':['bicameral system'],
    'gigantic':['gigantic statue'],
    'grieve':['grieve a loss','n','grief'],
    'studio':['recording studio'],
    'inhabit':['I inhabit the urban area of SZ','n','habitant'],
    'habitat':['a natural habitat'],
    'suicidal':['suicidal thoughts'],
    'bilateral':['bilateral agreement'],
    'clinic':['walk-in clinic','adj','clinical'],
    'memorable':['memorable moment','v','memorize'],
    'dazzle':['dazzle the audience'],
    'vast':['a vast expanse of land'],
    'underground':['underground movement'],
    'compete':['compete in a tournament','n','competition'],
    'prescription':['prescription medication'],
    'prescribe':['prescribe a treatment'],
    'crude':['crude oil'],
    'in vain':['efforts in vain'],
    'alley':['back alley'],
    'dolphin':['dolphin pod'],
    'platform':['online platform'],
    'appoint':['appoint a representative'],
    'characteristic':['defining characteristic'],
    'character':['moral character'],
    'altitude':['high altitude'],
    'contradiction':['logical contradiction'],
    'contradict':['contradict oneself'],
    'painstaking':['painstaking effort'],
    'pursuit':['in pursuit of'],
    'apportion':['apportion blame'],
    'accountable':['be held accountable for'],
    'finitude':['awareness of finitude'],
    'revelation':['sensational revelation'],
    'reveal':['reveal a secret'],
    'attainable':['attainable goals'],
    'dispensable':['I\'m not indispensable.'],
    'cuisine':['local cuisine'],
    'reputable':['reputable source'],
    'reputation':['build a reputation'],
    'overshadow':['overshadow by success'],
    'unparalleled':['unparalleled beauty'],
    'supersede':['supersede existing regulations'],
    'passionate':['a passionate speech'],
    'poisonous':['poisonous snake'],
    'poison':['antidote to poison'],
    'mysterious':['mysterious disappearance'],
    'spite':['Mosquitoes don\'t bite out of spite'],
    'divert':['divert a train'],
    'dissemination':['thermal dissemination'],
    'disseminate':['disseminate information'],
    'perpetual':['perpetual motion machine'],
    'perpetuate':['perpetuate a cycle of'],
    'column':['column in a newspaper'],
    'cater':['cater lunch'],
    'lobby':['a hotel lobby'],
    'flexible':['flexible schedules'],
    'penalty':['the death penalty'],
    'penalize':['penalize for non-compliance'],
    'comply':['comply with the law'],
    'racket':['a tennis racket'],
    'socket':['Plug the charger into the wall socket'],
    'capsule':['take a capsule'],
    'canteen':['a school canteen'],
    'aeronautics':['a professor of aeronautics.'],
    'adopt':['adopt pets'],
    'lease':['You claim to be a tenant, yet you have no lease.'],
    'conceal':['conceal identity'],
    'haphazard':['The books were stacked in a haphazard manner.'],
    'essential':['essential ingredient'],
    'urge':['She urged him to stay.'],
    'feasible':['a feasible plan'],
    'cereal':['Calbee cereal'],
    'slurry':['slurry pump'],
    'admission':['admission to the college'],
    'jaw':['jaw-dropping'],
    'subtract':['6 subtracted from 9 is 3.'],
    'linguistic':['linguistic diversity'],
    'aptitude':['aptitude test'],
    'lava':['lava flow'],
    'premier':['Premier League'],
    'enquiry':['make an enquiry'],
    'lawsuit':['file a lawsuit'],
    'pack':['a pack of dogs'],
    'animate':['animate objects'],
    'animation':['computer animation'],
    'availability':['check your availability'],
    'payable':['a 10% deposit is payable in advance'],
    'solicitor':['I need my solicitor.'],
    'departure':['departure lounge'],
    'depart':['depart from 3 for America'],
    'audit':['an annual audit'],
    'scamper':['scamper away'],
    'spiral':['spiral abyss'],
    'encode':['encode a message'],
    'scout':['scout for talents'],
    'regurgitate':['regurgitate food'],
    'propellant':['Rocket propellant'],
    'ejection':['ejection seat'],
    'eject':['eject from a vehicle'],
    'barrage':['a barrage of questions'],
    'intrigue':['This Mr. Sherlock Holmes intrigues me.'],
    'transition':['transition period'],
    'realm':['in the realm of literature'],
    'banner':['banner year'],
    'ounce':['an ounce of prevention is worth a pound of cure.'],
    'technique':['a traditional technique'],
    'stock':['stock market'],
    'stack':['stack up against'],
    'petrol':['We ran out of petrol'],
    'sorrow':['drown one\'s sorrows'],
    'arboreal':['arboreal animal'],
    'facade':['the facade of a church'],
    'post-mortem':['conduct a post-mortem'],
    'blunt':['a blunt refusal'],
    'pile':['a pile of work'],
    'post':['police post'],
    'stockpile':['the stockpile of nuclear weapon'],
    'indicate':['indicate interest'],
    'indication':['give no indication'],
    'hypothesis':['test a hypothesis'],
    'hypothetical':['a hypothetical question'],
    'mountainous':['a mountainous region'],
    'trim':['trim the fat'],
    'steady':['a steady barrage'],
    'dramatic':['a dramatic effect'],
    'amorphous':['amorphous material'],
    'blade':['a sharp blade'],
    'glimpse':['he caught a glimpse of her in the crowd'],
    'bulletin':['news bulletin'],
    'chapel':['a wedding chapel'],
    'subscribe':['subscribe apple music'],
    'foil':['aluminum foil'],
    'invoice':['this is your invoice'],
    'transmute':['lead can\'t be transmute into gold'],
    'acoustic':['acoustic guitar'],
    'breakthrough':['a scientific breakthrough'],
    'spiritual':['spiritual journey'],
    'concrete':['concrete evidence'],
    'generalize':['Don\'t over-generalize'],
    'clot':['a blood clot'],
    'prior':['a prior criminal record'],
    'exemplify':['exemplify the best'],
    'herdsman':['a herdsman and his flock'],
    'exploratory':['exploratory research'],
    'pasture':['The cattle were put out to pasture.'],
    'nutrient':['a lack of essential nutrient'],
    'nutritional':['nutritional value'],
    'nutritious':['nutritious fruit'],
    'plough':['plough a field'],
    'scrub':['scrub the floor'],
    'formality':['a mere formality'],
    'perk':['job perk'],
    'heighten':['heighten awareness'],
    'necessity':['Water is necessity in every procedure of making tofu.'],
    'disposable':['a disposable diaper'],
    'ingenuity':['a testament to human ingenuity'],
    'simplicity':['the beauty of simplicity'],
    'luxuriant':['I want luxuriant hair'],
    'consequential':['consequential decision'],
    'consequent':['consequent effects'],
    'consequence':['face the consequences'],
    'scour':['scour the area'],
    'murky':['murky waters'],
    'melatonin':['melatonin supplement'],
    'cue':['cue me'],
    'thermal':['hydrothermal vent'],
    'revolution':['The French revolution'],
    'romance':['an office romance'],
    'recurrent':['a recurrent theme'],
    'persist':['persist in efforts to do my best'],
    'stash':['stash money'],
    'species':['an extinguished species'],
    'competent':['competent authority'],
    'loose':['tie up loose ends'],
    'lose':['I lost my key'],
    'lost':['get lost in thought'],
    'loosen':['loosen up'],
    'carpentry':['carpentry skills'],
    'spreadsheet':['spreadsheet software'],
    'clerical':['clerical work'],
    'Sweden':['Sweden'],
    'myth':['bust a myth'],
    'buffet':['a buffet lunch'],
    'sauna':['take a sauna'],
    'settlement':['reach a settlement'],
    'otter':['playful otters'],
    'robber':['a bank robber'],
    'midday':['midday sun'],
    'massage':['massage oil'],
    'hoover':['to hoover up all the dust'],
    'hippo':['hungry hippo'],
    'cram':['cram for a test'],
    'cannibal':['cannibal tribes'],
    'annex':['annex a territory'],
    'wretch':['a poor wretch'],
    'wholesale':['wholesale prices'],
    'timetable':['train timetable'],
    'tertiary':['tertiary education'],
    'suntan':['suntan block'],
    'suite':['standard suite'],
    'spinose':['spinose plants'],
    'shear':['shear the sheep'],
    'urchin':['sea urchin'],
    'rubber':['rubber band'],
}

import random

# 用于跟踪每个单词的正确情况
attempts = 0
correct_answers = 0

while words:
    # 从字典中随机选择一个单词
    word = random.choice(list(words.keys()))
    print(f"Word: {word}")
    
    # 用户输入短语
    phrase_input = input("Enter the phrase of the word: ").lower()
    correct_phrase = words[word][0].lower()
    
    # 检查短语是否正确
    if phrase_input == correct_phrase:
        print("Correct phrase!")
        correct_answers += 1
    else:
        print(f"Incorrect phrase. The correct one is '{correct_phrase}'.")
    attempts += 1
    
    # 如果存在相关单词，检查相关单词是否正确
    if len(words[word]) > 1:
        relative_word_input = input("Enter the relative word (or press enter if none): ").lower()
        correct_relative_word = words[word][1].lower()
        
        if relative_word_input == correct_relative_word:
            print("Correct relative word!")
            correct_answers += 1
        else:
            print(f"Incorrect relative word. The correct one is '{correct_relative_word}'.")
        attempts += 1
    
    # 从字典中移除已经抽取的单词
    del words[word]
    
    # 检查是否还有单词，如果没有，结束循环
    if not words:
        print("All words have been practiced.")
        break

# 计算正确率
correct_rate = (correct_answers / attempts) * 100

# 生成报告
print("\nPractice Report:")
print(f"Total Attempts: {attempts}")
print(f"Correct Answers: {correct_answers}")
print(f"Accuracy Rate: {correct_rate:.2f}%") 